version: '3.8'

services:
  chatwithcuhksz:
    build: .
    container_name: chatwithcuhksz
    volumes:
      - linux-chatwithcuhksz:/opt/vcpkg
      - linux-cache:/var/cache
    ports:
      - 8080:8080
    environment:
      - APIBASE=https://api.nextapi.fun/v1/chat/completions
      - APIKEY=YOUR_API_KEY
volumes:
  linux-chatwithcuhksz:
    driver: local
  linux-cache:
    driver: local
