version: '3.8'

services:
  chatwifcusz:
    build: .
    container_name: chatwifcusz
    volumes:
      - linux-chatwifcusz:/opt/vcpkg
      - linux-cache:/var/cache
    ports:
      - 8080:8080
volumes:
  linux-chatwifcusz:
    driver: local
  linux-cache:
    driver: local
