version: '3.8'

services:
  chatwithcuhksz:
    build: .
    container_name: chatwithcuhksz
    volumes:
      - linux-chatwithcuhksz:/opt/vcpkg
      - linux-cache:/var/cache
    ports:
      - 8080:8080
volumes:
  linux-chatwithcuhksz:
    driver: local
  linux-cache:
    driver: local
